service: spring-boot-aws-lambda

frameworkVersion: "3.38.0"

provider:
  name: aws
  # update required Java Version
  runtime: java17
  stage: dev
  region: ap-southeast-1
  # update required memory upto 10GB
  memorySize: 1024
  timeout: 20
  deploymentBucket:
    name: dev-seller-lambda-code

package:
  artifact: target/spring-boot-aws-lambda-1.0.jar

functions:
  SpringBootApiHandler:
    handler: com.rkb.aws.handler.LambdaHandler
    name: spring-boot-aws-lambda
    runtime: java17
    description: Spring Boot API & Lambda deploy
    events:
      - http: ANY {proxy+}
